[platformio]
default_envs = esp32_master

; Cấu hình chung
[env]
framework = arduino
monitor_speed = 115200
build_flags = -I include ; Để các file trong src nhìn thấy secrets.h ở thư mục include

; --- Môi trường cho ESP32 Master ---
[env:esp32_master]
platform = espressif32
board = esp32dev
build_src_filter = +<esp32_master/> -<esp32_cam/> ; Chỉ lấy code master
lib_deps = 
    bodmer/TFT_eSPI
    links2004/ArduinoWebsockets
    tobozo/TJpg_Decoder
    knolleary/PubSubClient
    bblanchon/ArduinoJson
    Densaugeo/base64

; --- Môi trường cho ESP32 CAM ---
[env:esp32_cam]
platform = espressif32
board = esp32cam
build_src_filter = +<esp32_cam/> -<esp32_master/> ; Chỉ lấy code cam
lib_deps = 
    links2004/ArduinoWebsockets
    
; Cấu hình riêng cho ESP32-CAM (nếu cần)
board_build.partitions = huge_app.csv ; Tăng bộ nhớ app nếu code lớn